name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Fork
        uses: aormsby/fork-sync-with-upstream@v3.4.1
        with:
          target_sync_branch: develop
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: shlinkio/shlink
          upstream_sync_branch: develop
